language: php

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache/files

before_install:
  - composer require --dev --no-update symfony/symfony:$SYMFONY_VERSION

install:
  - composer install

script:
  - ./vendor/bin/phpunit

matrix:
  include:
    - php: 7.1
      env: SYMFONY_VERSION=3.4.x
    - php: 7.1
      env: SYMFONY_VERSION=4.3.x
    - php: 7.2
      env: SYMFONY_VERSION=3.4.x
    - php: 7.2
      env: SYMFONY_VERSION=4.3.x
    - php: 7.3
      env: SYMFONY_VERSION=3.4.x
    - php: 7.3
      env: SYMFONY_VERSION=4.3.x
  fast_finish: true
